-- Run this once in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 20),
  created_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  game text not null default '4x4',
  difficulty text not null,
  moves integer not null check (moves > 0),
  seconds integer not null check (seconds >= 0),
  created_at timestamptz not null default now()
);

create index if not exists scores_game_difficulty_moves_idx on public.scores(game, difficulty, moves, seconds);

alter table public.profiles enable row level security;
alter table public.scores enable row level security;

create policy "profiles are public" on public.profiles for select using (true);
create policy "users create own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);

create policy "scores are public" on public.scores for select using (true);
create policy "users insert own scores" on public.scores for insert with check (auth.uid() = user_id);

-- Optional helper view for a clean leaderboard.
create or replace view public.leaderboard_4x4 as
select difficulty, username, min(moves) as best_moves, min(seconds) as best_seconds
from public.scores
where game = '4x4'
group by difficulty, username;
